### ISSUE TITLE
[Q] array as key and array as value

### ISSUE THREAD

**Issue by tim-fastpay** [graphql/dataloader#192] opened 2019-07-23 04:01 UTC
I am caching array of object data with array of key(id) in dataloader.
Can I break into individual data and key pair and load in different model?

this is what Im getting
```DataLoader {
  _batchLoadFn: [Function],
  _options: undefined,
  _promiseCache: 
   Map {
     [ '1912',
     '1930',
     '1908',
     '1942',
     '1931',
     '1953',
     '1906',
     '1929',
     '1948' ] => Promise { <pending> },
     '1912' => Promise { <pending> },
     '1930' => Promise { <pending> },
     '1908' => Promise { <pending> },
     '1942' => Promise { <pending> },
     '1931' => Promise { <pending> },
     '1953' => Promise { <pending> },
     '1906' => Promise { <pending> },
     '1929' => Promise { <pending> },
     '1948' => Promise { <pending> } },
  _queue: 
   [ { key: [Array], resolve: [Function], reject: [Function] },
     { key: '1912', resolve: [Function], reject: [Function] },
     { key: '1930', resolve: [Function], reject: [Function] },
     { key: '1908', resolve: [Function], reject: [Function] },
     { key: '1942', resolve: [Function], reject: [Function] },
     { key: '1931', resolve: [Function], reject: [Function] },
     { key: '1953', resolve: [Function], reject: [Function] },
     { key: '1906', resolve: [Function], reject: [Function] },
     { key: '1929', resolve: [Function], reject: [Function] },
     { key: '1948', resolve: [Function], reject: [Function] } ] }
```

**Comment by ljukas** [comment] 2019-08-06 09:27
Array as value is totally fine. I'd not recommend using an array as key. Keys should be simple. If possible pass the array of keys into the .loadMany() function instead.

**Comment by motephyr** [comment] 2019-08-18 23:24
Hi, I made a package to handle this.
https://github.com/motephyr/dataloader-helper

If there is anything I should pay attention to or improve, please let me know.

**Comment by ljukas** [comment] 2019-08-19 09:18
While it is a nice package that removes some of the work around writing loaders I don't think your package helps with this specific problem @motephyr. The problem is about using arrays as keys and not about having to rewrite almost the same code for different loaders.

The original problem could be solved for example by taking the array of keys and stringifying it into a single string. Maybe you'd want to sort them first if there is any chance of them being a different order the next time you get the same array as a key.

**Comment by tim-fastpay** [comment] 2019-08-20 00:52
What I was asking was if there is a way to load a data when I cached array of object with array of ids (many to many) 

for example 
```[1,2,3,4] : [{id:1} ,{id:2} , {id:3}] 
```
expected result:```
load(1) = {id:1}```

**Comment by ljukas** [comment] 2019-08-22 08:59
If you have several keys you want to load at the same time you use the .loadMany(ids) function. If you then use the .load(id) function with an id that was in the loadMany function, then you will used the cached result, if the cache is not turned off.

**Comment by tim-fastpay** [comment] 2019-08-22 20:55
loadMany() doesn't work in my case because I have only one key which is an array.
loadMany([[1,2,3]) would work if I had {1:{}, 2:{}, 3:{}} this structure. My case is {[1,2,3]:[{},{},{}]}

**Comment by ljukas** [comment] 2019-08-23 08:34
That cannot be done, but I also see no reason for it to be done. Just flatten the array and use .loadMany and you will get back an array with your results?

Can you perhaps put your problem in an "use-case"? What kind of database operation do you want to do with this array? Why do you want to use an array as the key?

**Comment by leebyron** [comment] 2019-11-15 01:15
Closing this aging issue.

Seems like you may need to just be careful with either you batch function or use of `prime()` to ensure you're providing individual values instead of arrays.

DataLoader will interpret an array key as a single key, since there are cases where this is intended (and a `cacheKeyFn` is probably needed)

**Closed by leebyron** 2019-11-15 01:15 UTC
